<?php 
return array (
  'site_name' => '小猪微信平台',
  'site_title' => '小猪微信平台',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://yungou.180.haoid.cn',
  'site_my' => '小猪',
  'server_key' => '',
  'server_topdomain' => 'www.haoid.cn',
  'connectout' => '',
  'ischeckuser' => 'false',
  'reg_needmp' => 'true',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => '',
  'ipc' => '',
  'site_qq' => '932603923',
  'site_mp' => '932603923',
  'baidu_map_api' => 'syUQdxYRUzqPby3xSPCeDFzl',
  'site_email' => '123456@qq.com',
  'keyword' => '微信',
  'content' => '描述',
  'countsz' => '',
  'copyright' => '',
);